[package]
name = "indicatif_tut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = { version = "0.16", features = ["rayon"] }
peroxide = "0.31"
