[package]
name = "pyo3_tutorial"
version = "0.1.0"
authors = ["axect <edeftg@gmail.com>"]
edition = "2018"

[dependencies]
peroxide = "0.8"

[lib]
name = "pyo3_tutorial"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.6.0-alpha.4"
features = ["extension-module"]
