[package]
name = "bonsaidb_tut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bonsaidb = { version = "0.5.0", features = ["local"] }
peroxide = "0.34.3"
serde = { version = "1.0.195", features = ["derive"] }
